version: "3.5"

services:
  php_fpm:
    build: ./docker/php-fpm
    container_name: email_tester_php_fpm
    working_dir: /var/www/html/email-tester
    networks:
      - email_tester_network
    volumes:
      - ./:/var/www/html/email-tester

  nginx:
    build: ./docker/nginx
    container_name: email_tester_nginx
    working_dir: /var/www/html/email-tester
    networks:
      - email_tester_network
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/email-tester
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7
    container_name: email_tester_mysql
    networks:
      - email_tester_network
    environment:
      - MYSQL_DATABASE=email_tester_admin
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret

  mailhog:
    build: ./docker/mailhog
    container_name: email_tester_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - email_tester_network

networks:
  email_tester_network:
    driver: bridge
