version: "3.5"

volumes:
  email-mysql-data:
    driver: local

services:
  php_fpm:
    build: ./docker/php-fpm
    container_name: email_php_fpm
    working_dir: /var/www/
    networks:
      - email_network
    volumes:
      - ./:/var/www/

  nginx:
    build: ./docker/nginx
    container_name: email_nginx
    working_dir: /var/www/
    networks:
      - email_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7
    container_name: email_mysql
    networks:
      - email_network
    environment:
      - MYSQL_DATABASE=email
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret
    volumes:
      - email-mysql-data:/var/lib/mysql

  mailhog:
    build: ./docker/mailhog
    container_name: email_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - email_network

networks:
  email_network:
    driver: bridge
